apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: podinfo-app
spec:
  components:
    - name: backend
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/sympatheticmoose/podinfo-backend
        git:
          branch: main
        path: ./
    - name: frontend
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/sympatheticmoose/podinfo-frontend
        git:
          branch: main
        path: ./